<?php

namespace MG\MemoryGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComputerPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerPlayerRepository extends EntityRepository
{
}
