<?php

namespace MG\MemoryGameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
	public function getResultsGamesByUserId($player = null, $offset = null, $max = null)
	{
		$qb = $this->createQueryBuilder('r')
		->where('r.player = :player')
        ->setParameter('player', $player)
		->addOrderBy('g.playedAt', 'DESC');
	
		if($max) {
			$qb->setMaxResults($max);
		}
	
		if($offset) {
			$qb->setFirstResult($offset);
		}
	
		if($player) {
			$qb->join('r.player', 'hp')
			->addSelect('hp')
			->join('r.game', 'g')
			->addSelect('g')
			;
		}
	
		$query = $qb->getQuery();
	
		return $query->getResult();
	}
}
